name: Fetch 539 Latest 100

on:
  schedule:
    - cron: '0 16 * * *'  # 台灣時間每天 00:00（GitHub 是 UTC+0）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run fetch script
        run: python fetch539.py

      - name: Commit updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last100.txt debug.html
          git commit -m "Auto update last100.txt and debug.html"
          git push
