name: Parse 539 to last100.txt

on:
  push:
    paths:
      - debug.html
      - parse_539.py
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install beautifulsoup4

    - name: Run parse script
      run: python parse_539.py

    - name: Commit and push last100.txt
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add last100.txt
        git commit -m "Auto update last100.txt by parse"
        git push
